http_port: "1212"
mysql:
  host: "localhost:9306"
  database: "url_shortener"
  username: "root"
  password: "root"
  sslmode: "disable"
  max_idle_conns: "2"
  max_open_conns: "5"
  conn_max_lifetime: 3600000
  ping_interval: 5000
log_level: "debug"